[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
edition = "2024"
publish = false

[workspace.dependencies]
pepecore-array = { path = "crates/pepecore-array" }
pepecore = { path = "crates/pepecore" }