name: Release

on:
  workflow_dispatch:
    inputs:
      upload_to_internal_index:
        description: 'Upload wheels to internal index'
        required: false
        type: boolean
        default: false

concurrency:
  group: release-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-macos-arm64:
    name: Build Python (macOS arm64)
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Maturin build
        uses: PyO3/maturin-action@v1
        with:
          args: --release --out dist
          working-directory: crates/pepecore-py-bindings
          container: 'off'

      - name: Upload python wheels
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: wheels-macos-arm64
          path: crates/pepecore-py-bindings/dist

  python-manylinux-x86_64:
    name: Build python (Linux x86-64)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Maturin build
        uses: PyO3/maturin-action@v1
        with:
          args: --release --out dist
          working-directory: crates/pepecore-py-bindings
          manylinux: 'auto'

      - name: Upload python wheels
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: wheels-linux-x86_64
          path: crates/pepecore-py-bindings/dist

  python-manylinux-arm64:
    name: Build python (Linux arm64)
    runs-on: ubuntu-2404-arm-4-core
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Maturin build
        uses: PyO3/maturin-action@v1
        with:
          args: --release --out dist
          working-directory: crates/pepecore-py-bindings
          manylinux: 2_17

      - name: Upload python wheels
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: wheels-linux-arm64
          path: crates/pepecore-py-bindings/dist

  python-pypi-upload:
    name: Upload to PyPi
    needs:
      - python-macos-arm64
      - python-manylinux-x86_64
      - python-manylinux-arm64
    runs-on: ubuntu-latest
    steps:
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          path: wheels
          pattern: wheels-*
          merge-multiple: true

      - name: Upload to PyPi
        if: ${{ github.ref == 'refs/heads/main' && !github.event.inputs.upload_to_internal_index }}
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          working-directory: wheels
          command: upload
          args: ./*.whl

      - name: Upload to internal index
        if: ${{ github.event.inputs.upload_to_internal_index }}
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_REPOSITORY: rewaifu
          MATURIN_REPOSITORY_URL: https://pypi.shd.llc/rewaifu/stable
          MATURIN_USERNAME: ${{ secrets.PYPI_LOGIN }}
          MATURIN_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        with:
          working-directory: wheels
          command: upload
          args: ./*.whl